//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAttMainEdit
    {
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> AttEditID { get; set; }
        public Nullable<System.DateTime> EditDateTime { get; set; }
        public Nullable<System.DateTime> OldTimeIn { get; set; }
        public Nullable<System.DateTime> OldTimeOut { get; set; }
        public Nullable<System.DateTime> NewTimeOut { get; set; }
        public string EmpDate { get; set; }
        public Nullable<bool> Process { get; set; }
        public string OldDutyCode { get; set; }
        public Nullable<System.TimeSpan> OldDutyTime { get; set; }
        public string NewDutyCode { get; set; }
        public Nullable<System.TimeSpan> NewDutyTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public string OldRemarks { get; set; }
        public string NewRemarks { get; set; }
        public Nullable<short> OldShiftMin { get; set; }
        public Nullable<short> NewShiftMin { get; set; }
        public string DeptName { get; set; }
        public string SectionName { get; set; }
        public string DesignationName { get; set; }
        public int Expr1 { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> SecID { get; set; }
        public string CardNo { get; set; }
        public string NicNo { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string TypeName { get; set; }
        public string LocName { get; set; }
        public string ShiftName { get; set; }
        public short DeptID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<byte> Gender { get; set; }
    }
}
